# Generated by Django 4.0 on 2021-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafile',
            name='batch',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='metafile',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='metafile',
            unique_together={('batch', 'name')},
        ),
        migrations.AddIndex(
            model_name='metafile',
            index=models.Index(fields=['batch', 'name'], name='batch_name'),
        ),
    ]
